### PR TITLE
Added conflict resolution for unique column constraint

### PR DESCRIPTION
**Pull request by jush**

### CODE REVIEW

**Comment by SimonVT** [comment]
Thanks :) I'll look into releasing a new version this weekend.

**Comment by danielbeutel** [comment]
Great work @jush @SimonVT

**Comment by jomeno** [comment]
* **thumbs up** @ #24 but the documentation is inadequate. How do we use the @Unique annotation, how to set the ConflictResolutionType ?

**Comment by jush** [comment]
@jomeno I agree, some example/doc would be good. Moreover #30 might have changed things also.

**Pull request merged**
